@startuml

Main -> DependencyContainer: initializeContext()
DependencyContainer -> PackageScanner: findClasses(): classes

PackageScanner -> PackageScanner: findResourceDirectories(): resourceDir
PackageScanner -> PackageScanner: findClassesInDirectories(resourceDir)

DependencyContainer -> DependencyContainer: getComponentClasses(classes): compClasses
DependencyContainer -> DependencyContainer: initializeDependencyGraph(compClasses): graph
DependencyContainer -> DependencyContainer: instantiateDependencies(graph): graph

@enduml
