@startuml

PackageScanner -> PackageScanner: findResourceDirectories(): resourceDir
PackageScanner -> PackageScanner: findClassesInDirectories(resourceDir)

Main -> DependencyContainer: initializeContext()

DependencyContainer -> PackageScanner: getClasses(): classes
DependencyContainer -> DependencyContainer: getComponentClasses(classes): compClasses
DependencyContainer -> DependencyContainer: initializeDependencyGraph(compClasses): graph
DependencyContainer -> DependencyContainer: instantiateDependencies(graph): graph

@enduml
